version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  target-branch: dev
  labels:
  - dependencies
  ignore:
  - dependency-name: ReactiveUI.Fody
    versions:
    - 13.2.10
    - 13.2.2
  - dependency-name: Xamarin.AndroidX.Lifecycle.Runtime
    versions:
    - 2.3.0
    - 2.3.1
  - dependency-name: Microsoft.AppCenter.Crashes
    versions:
    - 4.2.0
  - dependency-name: Xamarin.CommunityToolkit
    versions:
    - 1.1.0
  - dependency-name: Microsoft.AppCenter.Analytics
    versions:
    - 4.2.0
  - dependency-name: Rg.Plugins.Popup
    versions:
    - 2.0.0.11
  - dependency-name: XF.Material
    versions:
    - 1.7.8
  - dependency-name: Acr.UserDialogs
    versions:
    - 7.1.0.481
  - dependency-name: Microsoft.CodeAnalysis
    versions:
    - 3.9.0
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.9.1
  - dependency-name: Moq
    versions:
    - 4.16.1
  - dependency-name: Xamarin.AndroidX.Arch.Core.Runtime
    versions:
    - 2.1.0.8
  - dependency-name: Xamarin.GooglePlayServices.Tasks
    versions:
    - 117.2.1
  - dependency-name: coverlet.collector
    versions:
    - 3.0.3
  - dependency-name: Xamarin.AndroidX.Lifecycle.Process
    versions:
    - 2.3.0
  - dependency-name: Xamarin.GooglePlayServices.Basement
    versions:
    - 117.6.0
  - dependency-name: Bogus
    versions:
    - 33.0.1
    - 33.0.2
  - dependency-name: Xamarin.AndroidX.Core
    versions:
    - 1.3.2.2
  - dependency-name: Microsoft.NETCore.UniversalWindowsPlatform
    versions:
    - 6.2.12
  - dependency-name: MarkdownSnippets.MsBuild
    versions:
    - 22.0.3
    - 23.0.1
    - 23.0.2
  - dependency-name: Uno.SourceGenerationTasks
    versions:
    - 3.0.0
  - dependency-name: Humanizer
    versions:
    - 2.8.26
