name: Publish Documentation
on:
  push:
    branches: [ master, main, docupdate, preview ]
    paths:
    - "docs/**"

jobs:

  ###################################################
  # DOCS
  ###################################################

  build:
    name: Publish
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.202' # SDK Version to use.

    - name: Publish-Documentation
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.DOCS_GITHUB_TOKEN }}
      run: |
        dotnet restore ./docs/docs.csproj
        dotnet run -p ./docs/docs.csproj -- deploy
