name: Build Samples

on:
  push:
    branches: [ master, main, dev ]
    paths:
    - "samples/**"
  pull_request:
    branches: [ master, 'main', dev ]
    paths:
    - "samples/**"

jobs:
  Android:
    runs-on: macos-latest
    steps:
    #- name: setup-xamarin
      # uses: maxim-lobanov/setup-xamarin@v1
      # with:
        # mono-version: 6.6 # specify version in '<major>.<minor>' format
        # xamarin-ios-version: 13 # specify version in '<major>' format
        # xamarin-mac-version: latest # specify 'latest' keyword to pick up the latest available version
        # xamarin-android-version: 10.1.3.7 # specify full version; it is not recomended option because your pipeline can be broken suddenly in future
        # xcode-version: 11.x # set the latest available Xcode 11

    - uses: actions/checkout@v1
    - name: Android
      run: msbuild samples/Samples.Android/Samples.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release
    #- uses: Tlaster/android-sign@v1
        # name: Sign app APK
        # with:
        #   releaseDirectory: |
        #     app/build/outputs/apk/release
        #     app/build/outputs/bundle/release
        #   signingKeyBase64: ${{ secrets.SIGNING_KEY }}
        #   output: build/release/signed
        #   alias: ${{ secrets.ALIAS }}
        #   keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
        #   keyPassword: ${{ secrets.KEY_PASSWORD }}
        # env:
        #   BUILD_TOOLS_VERSION: "30.0.2"

  iOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: iOS
      run: msbuild samples/Samples.iOS/Samples.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhone /p:Configuration=Release